### PR TITLE
Add skeleton of Django project and blog app

### PR DESCRIPTION
**Pull request by PetrushynskyiOleksii**
Ref #11

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
you don't want to close #11 just yet

**Comment by PetrushynskyiOleksii** [comment]
@webknjaz 'solve' doesn't close issue or it needn't to write at this PR?

**Comment by webknjaz** [comment]
basically, it's a lie. it solves some part of that issue.
I'd use `Ref #11` instead

**Comment by PetrushynskyiOleksii** [comment]
Oh, well thank u.
I'll use in the next PR

**Pull request merged**
